self
exc_class
callable_obj
exception
