def test_context_manager_with_magic_mock(self):
    mock = MagicMock()
    with self.assertRaises(TypeError):
        with mock:
            ('foo' + 3)
    mock.__enter__.assert_called_with()
    self.assertTrue(mock.__exit__.called)
