def test_new_callable_incompatible_with_autospec(self):
    self.assertRaises(ValueError, patch, foo_name, new_callable=MagicMock, autospec=True)
    self.assertRaises(ValueError, patch.object, Foo, 'f', new_callable=MagicMock, autospec=True)
