{
  try {
    return callable.call();
  }
 catch (  Exception ex) {
    return null;
  }
}
