def test_tracebacks(self):

    @patch.object(Foo, 'f', object())
    def test():
        raise AssertionError
    try:
        test()
    except:
        err = sys.exc_info()
    result = unittest2.TextTestResult(None, None, 0)
    traceback = result._exc_info_to_string(err, self)
    self.assertIn('raise AssertionError', traceback)
