{
  try {
    return future.get();
  }
 catch (  ExecutionException e) {
    Throwable cause=e.getCause();
    Throwables.propagateIfPossible(cause,IOException.class,InterruptedException.class);
    throw new RuntimeException(e);
  }
}
