{
  ev.setFailFast(false);
  try {
    eval(lines);
    fail("checkErrorContains(String, String...): There was no error");
  }
 catch (  EvalException e) {
    assertThat(e.getMessage()).contains(errorMsg);
  }
}
