def test_assert_called_with(self):
    mock = Mock()
    mock()
    mock.assert_called_with()
    self.assertRaises(AssertionError, mock.assert_called_with, 1)
    mock.reset_mock()
    self.assertRaises(AssertionError, mock.assert_called_with)
    mock(1, 2, 3, a='fish', b='nothing')
    mock.assert_called_with(1, 2, 3, a='fish', b='nothing')
