def test_new_callable_incompatible_with_new(self):
    self.assertRaises(ValueError, patch, foo_name, new=object(), new_callable=MagicMock)
    self.assertRaises(ValueError, patch.object, Foo, 'f', new=object(), new_callable=MagicMock)
